"""add_api_credentials_and_unique_user_id

Revision ID: ecb24f5720c3
Revises: 1895143b2b8c
Create Date: 2026-09-15 13:43:49.073924+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers
revision: str = 'ecb24f5720c3'
down_revision: Union[str, None] = '1895143b2b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_id', sa.Integer(), nullable=True, comment='Telegram API ID for this account (from my.telegram.org)'))
        batch_op.add_column(sa.Column('api_hash', sa.String(length=255), nullable=True, comment='Telegram API Hash for this account (from my.telegram.org)'))
        batch_op.create_unique_constraint('uq_telegram_accounts_user_id', ['user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_telegram_accounts_user_id', type_='unique')
        batch_op.drop_column('api_hash')
        batch_op.drop_column('api_id')

    # ### end Alembic commands ###
